// app/(dashboard)/reports/page.tsx
import { createClient } from '@/lib/supabase/server'
import { getAdminStats, getProjectsByRegion, getSubmissionsByStatus, getMonthlySubmissionTrend } from '@/lib/actions/analytics'
import { notFound } from 'next/navigation'
import { format } from 'date-fns'
import {
  BarChart3, Download, Printer, FolderKanban,
  Camera, CheckCircle2, AlertTriangle, Users,
  MapPin, TrendingUp, Calendar,
} from 'lucide-react'
import {
  SubmissionStatusChart,
  ProjectsByRegionChart,
  SubmissionTrendChart,
} from '@/components/dashboard/SubmissionsChart'
import { PrintButton } from '@/components/reports/PrintButton'

export const dynamic = 'force-dynamic'

export default async function ReportsPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const { data: profile } = await supabase
    .from('users')
    .select('role, full_name')
    .eq('id', user?.id ?? '')
    .single()

  if (!['admin', 'official'].includes(profile?.role ?? '')) notFound()

  const [stats, regionData, statusData, trendData] = await Promise.all([
    getAdminStats(),
    getProjectsByRegion(),
    getSubmissionsByStatus(),
    getMonthlySubmissionTrend(),
  ])

  // Fetch recent projects for the report
  const { data: recentProjects } = await supabase
    .from('projects')
    .select('name, project_number, status, completion_percentage, location_region, budget_total')
    .order('created_at', { ascending: false })
    .limit(10)

  const generatedAt = format(new Date(), 'PPP p')
  const reportPeriod = `${format(new Date(new Date().getFullYear(), 0, 1), 'MMM d, yyyy')} — ${format(new Date(), 'MMM d, yyyy')}`

  return (
    <div className="mx-auto max-w-5xl px-4 py-8" id="report-content">
      {/* Header */}
      <div className="mb-8 flex items-start justify-between gap-4 flex-wrap">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <BarChart3 className="h-6 w-6 text-blue-600" />
            <h1 className="text-2xl font-bold text-slate-900">System Report</h1>
          </div>
          <p className="text-slate-500 text-sm">
            Generated by {profile?.full_name} · {generatedAt}
          </p>
          <p className="text-slate-400 text-xs mt-0.5">Period: {reportPeriod}</p>
        </div>
        <div className="flex items-center gap-2 print:hidden">
          <PrintButton />
        </div>
      </div>

      {/* Executive Summary */}
      <section className="mb-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 className="mb-4 text-lg font-bold text-slate-900 flex items-center gap-2">
          <TrendingUp className="h-5 w-5 text-blue-600" />
          Executive Summary
        </h2>
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          {[
            { label: 'Total Projects',  value: stats.totalProjects,    icon: FolderKanban, color: 'text-blue-600',  bg: 'bg-blue-50' },
            { label: 'Submissions',     value: stats.totalSubmissions,  icon: Camera,       color: 'text-purple-600', bg: 'bg-purple-50' },
            { label: 'Approved',        value: stats.approvedSubmissions, icon: CheckCircle2, color: 'text-green-600', bg: 'bg-green-50' },
            { label: 'Flagged',         value: stats.flaggedSubmissions, icon: AlertTriangle, color: 'text-red-600',  bg: 'bg-red-50' },
          ].map(stat => {
            const Icon = stat.icon
            return (
              <div key={stat.label} className={`rounded-xl p-4 ${stat.bg}`}>
                <Icon className={`h-5 w-5 mb-2 ${stat.color}`} />
                <p className="text-2xl font-bold text-slate-900">{stat.value}</p>
                <p className="text-xs text-slate-500 mt-0.5">{stat.label}</p>
              </div>
            )
          })}
        </div>

        {/* Key metrics */}
        <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3">
          <div className="rounded-xl border border-slate-100 p-3 text-sm">
            <p className="text-slate-400 text-xs">GPS Verification Rate</p>
            <p className="font-bold text-slate-800 text-lg mt-0.5">{stats.gpsVerificationRate}%</p>
            <p className="text-xs text-slate-400">of submissions approved</p>
          </div>
          <div className="rounded-xl border border-slate-100 p-3 text-sm">
            <p className="text-slate-400 text-xs">Active Projects</p>
            <p className="font-bold text-slate-800 text-lg mt-0.5">{stats.activeProjects}</p>
            <p className="text-xs text-slate-400">of {stats.totalProjects} total</p>
          </div>
          <div className="rounded-xl border border-slate-100 p-3 text-sm">
            <p className="text-slate-400 text-xs">Flagged Projects</p>
            <p className={`font-bold text-lg mt-0.5 ${stats.flaggedProjects > 0 ? 'text-red-600' : 'text-green-600'}`}>
              {stats.flaggedProjects}
            </p>
            <p className="text-xs text-slate-400">require investigation</p>
          </div>
        </div>
      </section>

      {/* Charts */}
      <div className="mb-8 grid gap-6 sm:grid-cols-2">
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <h2 className="mb-4 font-semibold text-slate-900">Submissions by Status</h2>
          <SubmissionStatusChart data={statusData} />
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <h2 className="mb-4 font-semibold text-slate-900">Projects by Region</h2>
          <ProjectsByRegionChart data={regionData} />
        </section>
      </div>

      <section className="mb-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <h2 className="mb-4 font-semibold text-slate-900">Submission Trend (6 months)</h2>
        <SubmissionTrendChart data={trendData} />
      </section>

      {/* Projects table */}
      <section className="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
        <div className="border-b border-slate-100 px-5 py-4 flex items-center justify-between">
          <h2 className="font-semibold text-slate-900 flex items-center gap-2">
            <FolderKanban className="h-4 w-4 text-slate-400" />
            Recent Projects
          </h2>
          <span className="text-xs text-slate-400">Last 10 projects</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-slate-100 bg-slate-50">
                <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-400">Project</th>
                <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-400 hidden sm:table-cell">Region</th>
                <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-400">Status</th>
                <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-slate-400">Progress</th>
                <th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wide text-slate-400 hidden md:table-cell">Budget</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {(recentProjects ?? []).map((p: any) => (
                <tr key={p.project_number} className="hover:bg-slate-50">
                  <td className="px-4 py-3">
                    <p className="text-sm font-medium text-slate-800">{p.name}</p>
                    <p className="text-xs text-slate-400">{p.project_number}</p>
                  </td>
                  <td className="px-4 py-3 hidden sm:table-cell">
                    <span className="text-xs text-slate-500 flex items-center gap-1">
                      <MapPin className="h-3 w-3" />{p.location_region}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <span className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold ${
                      p.status === 'active' ? 'bg-green-100 text-green-700' :
                      p.status === 'completed' ? 'bg-blue-100 text-blue-700' :
                      p.status === 'flagged' ? 'bg-red-100 text-red-700' :
                      'bg-slate-100 text-slate-600'
                    }`}>
                      {p.status}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <div className="w-20 h-1.5 rounded-full bg-slate-100 overflow-hidden">
                        <div
                          className="h-full rounded-full bg-blue-500"
                          style={{ width: `${p.completion_percentage}%` }}
                        />
                      </div>
                      <span className="text-xs font-medium text-slate-600">{p.completion_percentage}%</span>
                    </div>
                  </td>
                  <td className="px-4 py-3 text-right hidden md:table-cell">
                    <span className="text-xs text-slate-600">
                      GH₵ {Number(p.budget_total ?? 0).toLocaleString()}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* Footer */}
      <div className="mt-6 text-center text-xs text-slate-400 print:block">
        <p>Government Project Monitoring System — Confidential</p>
        <p>Generated: {generatedAt}</p>
      </div>
    </div>
  )
}